# Generated by Django 4.0.6 on 2022-07-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_menu',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='food_menu',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='infofood',
            name='menu',
        ),
        migrations.AddField(
            model_name='infofood',
            name='total_food_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Food_Menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
